### PR TITLE
lscan added.

### PR DESCRIPTION
**Pull request by zmsp**

### CODE REVIEW

**Comment by Oznomal** [comment]
Quick question, is the console working for anyone at all? I think I see
where a lot of stuff got deleted with a merge but I want to make sure that
it's not working first.

**Comment by Oznomal** [comment]
Like on the master branch?

**Comment by gwijeratne** [comment]
I will check when I  get home. It was working locally for me last time I
checked.

**Comment by gwijeratne** [comment]
I just checked out the fresh code from the repo and it is working fine.

**Comment by Oznomal** [comment]
Yeah, I pulled down a fresh version as well but it doesn't seem to be
working for me. I did a little digging back through the commits and it
looks like when you pushed the code for the gopher service you also made a
lot of changes that to the mower service as well, some of which kind of
broke things.

https://github.com/Oznomal/osmowsis-final-project/commit/174de79031d20f888d0f33428ef35c470ba6b730


It looks like you removed the dependency for the sidebar controller, which
is the primary point of communication for all of the UI control stuff that
is happening on the sidebar, so the console section at the bottom of the
sidebar that was displaying the moves after each turn is no longer getting
updated. I figured you may have done this because of some circular
dependencies, which are definitely in some spots but I haven't really put a
lot of effort into resolving them quite yet because we are kind of short on
time, so the lazy annotation seems to be working fine for now .... Also,
some of them will be a little hard to resolve because of the controller
architecture and the fact that controllers need to depend on services but
services also need to be able to update the UI through the controller, so
the Lazy annotation has been a crutch until we can get all of the features
implemented and then time bearing some more models could have been created
to kind break out those dependencies.

Also, when mowers collide the mower that gets collided into (the one not
moving) does not get removed from the simulation monitor, this is because
you commented out the  updateSimStateForMowerMove  method on line 213 and
instead called it on line 94 which only ever gets reached if the move is
considered valid (no collisions etc), this causes the other mower not to
get removed on the actual sim

It's no biggie, but we are deff going to have to resolve some of the
conflicts because the overall behavior is quite buggy right now, but the
gopher tracking the closest mowers seems to be working great!

**Comment by Oznomal** [comment]
I cut out a new branch that should have resolved the conflicts with the
commit you had and the one I had, it is labeled OSMOWSIS-5 and includes the
following changes:

1. The LScan that Zobair implemented
2. The Gopher Service and energy stuff that Gayan implemented and merged
into master yesterday in the commit listed above
3, The UI changes that I implemented for the console as well as some
changes that I had implemented to display the final results and handle when
the stop button is clicked.


Everything seems to be meshing together now annd the following issues were
corrected

- Mowers not being moved off of the simulation when they were involved in a
collision with another mower
- The console on the sidebar not being updated when the next button was
being clicked
- The circular dependency that involved the mower service depending on the
gopher service .... and the gopher service depending on the mower service.
Now, the gopher service depends on the mower service since when the gophers
move into a mower the mower needs to be removed, but the mower service no
longer has a dependency on the gopher service.

Issues that are still present and this branch did not fix:

- The gopher service needs to update the UI when the gophers move, so that
the console can display those changes as well (I will cut a new branch
based on this branch and handle this now)
- There is an off by 1 error with the way that I am getting the next mower,
which causes mower 1 to still take a move on the first turn of the gopher
moves ... pretty sure I just need to put the check higher or change the way
we are getting the current mower. I'll look into this next
- We have the LScan functionality, but I don't think our strategy takes
that into account, so we probably need to make some updates to our
implementation of determining the next move to take that into account

I have not merged this into master because I am unsure what everyone is
working on and you may be making changes that are based on the current
version of master and this may break those, so I would ask that you pull
this down and run it locally to see if it looks to be working as you
expect.

Please don't make any commits to this branch .... feel free to cut a new
branch off of it, but please don't commit anything to directly to it.

**Pull request merged**
